licenses(["notice"])  # Apache-2.0 OR MIT

package(default_visibility = ["//visibility:public"])

exports_files([
    "apply-libmodsecurity-patch.sh",
    "libmodsecurity-set-var-nonthrow.patch",
    "modsecurity_source.BUILD",
])
