#!/usr/bin/env python3

"""Build a GitHub Actions QA summary from the generated Markdown reports."""

import argparse
import json
from pathlib import Path
import shutil


REPORTS = {
    "crs": (
        "OWASP CRS compatibility",
        Path("crs-compatibility-linux-amd64/crs-compatibility-report.md"),
        "crs-compatibility-report.md",
    ),
    "qualification": (
        "Qualification benchmark",
        Path("qualification-benchmark/qualification-benchmark.md"),
        "qualification-benchmark-report.md",
    ),
    "body_pressure": (
        "Body-pressure stress",
        Path("body-pressure-stress/qualification-benchmark.md"),
        "body-pressure-stress-report.md",
    ),
}


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--artifacts-directory", type=Path, default=Path("artifacts"))
    parser.add_argument(
        "--summary-output",
        type=Path,
        default=Path("artifacts/ci-report-summary/qa-summary.md"),
    )
    parser.add_argument(
        "--preview-directory",
        type=Path,
        default=Path("artifacts/ci-report-previews"),
    )
    return parser.parse_args()


def markdown_without_title(markdown):
    lines = markdown.splitlines()
    if lines and lines[0].startswith("# "):
        lines = lines[1:]
        while lines and not lines[0].strip():
            lines.pop(0)
    return "\n".join(lines).rstrip()


def markdown_section(markdown, heading):
    lines = markdown.splitlines()
    selected = []
    in_section = False
    for line in lines:
        if line == heading:
            in_section = True
            continue
        if in_section and line.startswith("## "):
            break
        if in_section:
            selected.append(line)
    while selected and not selected[0].strip():
        selected.pop(0)
    return "\n".join(selected).rstrip()


def workflow_data(value):
    return str(value).replace("%", "%25").replace("\r", "%0D").replace("\n", "%0A")


def workflow_property(value):
    return workflow_data(value).replace(":", "%3A").replace(",", "%2C")


def emit_annotation(level, title, message):
    print(
        f"::{level} title={workflow_property(title)}::{workflow_data(message)}",
        flush=True,
    )


def benchmark_annotations(json_path, title):
    if not json_path.is_file():
        return
    try:
        result = json.loads(json_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        emit_annotation("warning", title, f"Unable to read benchmark JSON: {error}")
        return
    level = "error" if result.get("enforced") else "warning"
    for violation in result.get("violations", []):
        emit_annotation(level, title, violation)


def build_summary(artifacts_directory, preview_directory):
    lines = [
        "# QA report preview",
        "",
        "Reports generated by the Linux QA job are rendered below. Full JSON and diagnostic "
        "output remain available as workflow artifacts.",
        "",
    ]
    availability = []
    preview_directory.mkdir(parents=True, exist_ok=True)

    for key, (title, relative_path, preview_name) in REPORTS.items():
        report_path = artifacts_directory / relative_path
        lines.extend([f"## {title}", ""])
        if not report_path.is_file():
            lines.extend(
                [
                    "> This report was not produced. An earlier QA stage may have failed or "
                    "the stage may not have started.",
                    "",
                ]
            )
            availability.append((title, "Not produced"))
            continue

        markdown = report_path.read_text(encoding="utf-8")
        if key == "crs":
            rendered = markdown_section(markdown, "## Summary")
        else:
            rendered = markdown_without_title(markdown)
        lines.extend([rendered or "> The report contained no renderable summary.", ""])
        shutil.copyfile(report_path, preview_directory / preview_name)
        availability.append((title, "Available"))

    lines.extend(
        [
            "## Report availability",
            "",
            "| Report | Status |",
            "| --- | --- |",
        ]
    )
    lines.extend(f"| {title} | {status} |" for title, status in availability)
    lines.append("")
    return "\n".join(lines)


def main():
    args = parse_args()
    summary = build_summary(args.artifacts_directory, args.preview_directory)
    args.summary_output.parent.mkdir(parents=True, exist_ok=True)
    args.summary_output.write_text(summary, encoding="utf-8")

    benchmark_annotations(
        args.artifacts_directory
        / "qualification-benchmark/qualification-benchmark.json",
        "Qualification benchmark threshold",
    )
    benchmark_annotations(
        args.artifacts_directory / "body-pressure-stress/qualification-benchmark.json",
        "Body-pressure diagnostic threshold",
    )


if __name__ == "__main__":
    main()
